// <auto-generated />
using System;
using Catalog.Infrastructure.Implementation.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Catalog.Infrastructure.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Catalog.Domain.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = new Guid("878bc0af-6692-43f2-a131-32e5d6a22532"),
                            Description = "GymShark is a fitness apparel, manufacturer & online retailer based in the United Kingdom.",
                            Name = "GymShark"
                        },
                        new
                        {
                            Id = new Guid("254d8bb7-fd25-4c80-ab2f-24acbcab94c8"),
                            Description = "Adidas is a global German company that makes shoes, clothes, and sports gear.",
                            Name = "Adidas"
                        },
                        new
                        {
                            Id = new Guid("6ca12909-23a9-4b62-a519-53e8e803e387"),
                            Description = "Nike is the world's leading sports brand, designing and selling athletic footwear, apparel, and equipment.",
                            Name = "Nike"
                        },
                        new
                        {
                            Id = new Guid("b56a84d8-f6d7-4831-bc43-eb6b087f63b9"),
                            Description = "Diadora is an Italian sportswear and footwear company founded in 1948 in Caerano di San Marco, Italy.",
                            Name = "Diadora"
                        });
                });

            modelBuilder.Entity("Catalog.Domain.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0530e8f-c985-461d-b5ca-cce60adebe9e"),
                            Name = "Shirts"
                        },
                        new
                        {
                            Id = new Guid("2abd90b8-845a-45f3-8081-9a49198105fb"),
                            Name = "Pants"
                        },
                        new
                        {
                            Id = new Guid("79fbd40c-96b0-4daa-a53b-0664d3a626d0"),
                            Name = "Shoes"
                        },
                        new
                        {
                            Id = new Guid("e9ef65ef-a066-427d-88b0-7c7845b9c693"),
                            Name = "Caps"
                        });
                });

            modelBuilder.Entity("Catalog.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cf198219-da46-4264-b5ed-7565a56d26fe"),
                            BrandId = new Guid("878bc0af-6692-43f2-a131-32e5d6a22532"),
                            CategoryId = new Guid("a0530e8f-c985-461d-b5ca-cce60adebe9e"),
                            Name = "Cottom Sweat Shirt"
                        },
                        new
                        {
                            Id = new Guid("59842595-1129-439e-a84f-dff86c261a3c"),
                            BrandId = new Guid("878bc0af-6692-43f2-a131-32e5d6a22532"),
                            CategoryId = new Guid("a0530e8f-c985-461d-b5ca-cce60adebe9e"),
                            Name = "Cottom Sweat Jogger"
                        },
                        new
                        {
                            Id = new Guid("99199924-e42c-4dcf-a2ea-dc482bc3c7be"),
                            BrandId = new Guid("254d8bb7-fd25-4c80-ab2f-24acbcab94c8"),
                            CategoryId = new Guid("a0530e8f-c985-461d-b5ca-cce60adebe9e"),
                            Name = "Dry Sweat Shirt"
                        },
                        new
                        {
                            Id = new Guid("4db2c7d5-fc02-4bc4-a245-9f0a5396083a"),
                            BrandId = new Guid("254d8bb7-fd25-4c80-ab2f-24acbcab94c8"),
                            CategoryId = new Guid("a0530e8f-c985-461d-b5ca-cce60adebe9e"),
                            Name = "Dry Sweat Shirt"
                        },
                        new
                        {
                            Id = new Guid("8a8038f9-9df9-4a7b-a76e-414ae1312827"),
                            BrandId = new Guid("6ca12909-23a9-4b62-a519-53e8e803e387"),
                            CategoryId = new Guid("e9ef65ef-a066-427d-88b0-7c7845b9c693"),
                            Name = "Baseball Cap Nike"
                        },
                        new
                        {
                            Id = new Guid("097c365a-f057-4de1-aaaf-829516c25467"),
                            BrandId = new Guid("6ca12909-23a9-4b62-a519-53e8e803e387"),
                            CategoryId = new Guid("79fbd40c-96b0-4daa-a53b-0664d3a626d0"),
                            Name = "Pegasus Nike Runners"
                        },
                        new
                        {
                            Id = new Guid("0064db26-87a7-4da2-aa13-c72096303b10"),
                            BrandId = new Guid("b56a84d8-f6d7-4831-bc43-eb6b087f63b9"),
                            CategoryId = new Guid("2abd90b8-845a-45f3-8081-9a49198105fb"),
                            Name = "Cottom Sweat Jogger"
                        },
                        new
                        {
                            Id = new Guid("a4aa9101-5802-4ec9-a556-468a784dcff6"),
                            BrandId = new Guid("b56a84d8-f6d7-4831-bc43-eb6b087f63b9"),
                            CategoryId = new Guid("a0530e8f-c985-461d-b5ca-cce60adebe9e"),
                            Name = "Cottom Sweat Shirt"
                        });
                });

            modelBuilder.Entity("Catalog.Domain.Product", b =>
                {
                    b.HasOne("Catalog.Domain.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Catalog.Domain.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Catalog.Domain.Stock", "Stocks", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("InStore")
                                .HasColumnType("int");

                            b1.Property<int>("Online")
                                .HasColumnType("int");

                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Size")
                                .IsRequired()
                                .HasMaxLength(5)
                                .HasColumnType("nvarchar(5)");

                            b1.HasKey("Id");

                            b1.HasIndex("ProductId");

                            b1.ToTable("ProductStocks", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ProductId");

                            b1.HasData(
                                new
                                {
                                    Id = new Guid("57904706-5617-43f7-93b1-1693c11cba99"),
                                    InStore = 10,
                                    Online = 50,
                                    ProductId = new Guid("cf198219-da46-4264-b5ed-7565a56d26fe"),
                                    Size = "S"
                                },
                                new
                                {
                                    Id = new Guid("2b068228-d46c-4cbb-bc37-db70f1b284c9"),
                                    InStore = 10,
                                    Online = 50,
                                    ProductId = new Guid("cf198219-da46-4264-b5ed-7565a56d26fe"),
                                    Size = "M"
                                },
                                new
                                {
                                    Id = new Guid("03a001e7-168d-43a5-a599-a07b1ad3a692"),
                                    InStore = 10,
                                    Online = 50,
                                    ProductId = new Guid("cf198219-da46-4264-b5ed-7565a56d26fe"),
                                    Size = "L"
                                },
                                new
                                {
                                    Id = new Guid("6bc34f4b-6603-47b4-9d7a-1e1091ba9d0e"),
                                    InStore = 10,
                                    Online = 50,
                                    ProductId = new Guid("59842595-1129-439e-a84f-dff86c261a3c"),
                                    Size = "S"
                                },
                                new
                                {
                                    Id = new Guid("8cb80b90-a919-4ee6-b0f1-426c7b0ef189"),
                                    InStore = 10,
                                    Online = 50,
                                    ProductId = new Guid("59842595-1129-439e-a84f-dff86c261a3c"),
                                    Size = "M"
                                },
                                new
                                {
                                    Id = new Guid("e537f5f6-db4e-46a5-8595-8644b13265bf"),
                                    InStore = 10,
                                    Online = 50,
                                    ProductId = new Guid("59842595-1129-439e-a84f-dff86c261a3c"),
                                    Size = "L"
                                },
                                new
                                {
                                    Id = new Guid("932aa8ef-59a6-47da-ad4c-367c2db2f5a2"),
                                    InStore = 10,
                                    Online = 50,
                                    ProductId = new Guid("99199924-e42c-4dcf-a2ea-dc482bc3c7be"),
                                    Size = "S"
                                },
                                new
                                {
                                    Id = new Guid("15fad713-5f5b-4c79-90e4-cc0d64eacf4b"),
                                    InStore = 10,
                                    Online = 50,
                                    ProductId = new Guid("99199924-e42c-4dcf-a2ea-dc482bc3c7be"),
                                    Size = "M"
                                },
                                new
                                {
                                    Id = new Guid("3546c25a-03c4-4fd1-93dd-faef228a6035"),
                                    InStore = 10,
                                    Online = 50,
                                    ProductId = new Guid("99199924-e42c-4dcf-a2ea-dc482bc3c7be"),
                                    Size = "L"
                                },
                                new
                                {
                                    Id = new Guid("666eb407-dc0c-4db7-ba61-f63b013cef82"),
                                    InStore = 10,
                                    Online = 50,
                                    ProductId = new Guid("4db2c7d5-fc02-4bc4-a245-9f0a5396083a"),
                                    Size = "S"
                                },
                                new
                                {
                                    Id = new Guid("dc8dfa43-4cf6-4106-9b42-de66c0cda92e"),
                                    InStore = 10,
                                    Online = 50,
                                    ProductId = new Guid("4db2c7d5-fc02-4bc4-a245-9f0a5396083a"),
                                    Size = "M"
                                },
                                new
                                {
                                    Id = new Guid("eb58cdd8-0672-473a-b403-b695a2527d8d"),
                                    InStore = 10,
                                    Online = 50,
                                    ProductId = new Guid("4db2c7d5-fc02-4bc4-a245-9f0a5396083a"),
                                    Size = "L"
                                },
                                new
                                {
                                    Id = new Guid("25b35ac8-3d7c-4513-a58e-880cb3a96062"),
                                    InStore = 10,
                                    Online = 50,
                                    ProductId = new Guid("8a8038f9-9df9-4a7b-a76e-414ae1312827"),
                                    Size = "S"
                                },
                                new
                                {
                                    Id = new Guid("59cced59-0749-4b61-a2b8-d1422348530c"),
                                    InStore = 10,
                                    Online = 50,
                                    ProductId = new Guid("8a8038f9-9df9-4a7b-a76e-414ae1312827"),
                                    Size = "M"
                                },
                                new
                                {
                                    Id = new Guid("24de1cbc-39cf-491a-b247-687e6dd1399d"),
                                    InStore = 10,
                                    Online = 50,
                                    ProductId = new Guid("8a8038f9-9df9-4a7b-a76e-414ae1312827"),
                                    Size = "L"
                                },
                                new
                                {
                                    Id = new Guid("5c787691-f278-4fd7-be10-5afc6bda1292"),
                                    InStore = 10,
                                    Online = 50,
                                    ProductId = new Guid("0064db26-87a7-4da2-aa13-c72096303b10"),
                                    Size = "S"
                                },
                                new
                                {
                                    Id = new Guid("3aedd23a-4e5e-46c3-9c0e-110fb4392d55"),
                                    InStore = 10,
                                    Online = 50,
                                    ProductId = new Guid("0064db26-87a7-4da2-aa13-c72096303b10"),
                                    Size = "M"
                                },
                                new
                                {
                                    Id = new Guid("93d82da8-8cf7-496f-85ed-8b8515607bae"),
                                    InStore = 10,
                                    Online = 50,
                                    ProductId = new Guid("0064db26-87a7-4da2-aa13-c72096303b10"),
                                    Size = "L"
                                },
                                new
                                {
                                    Id = new Guid("e0bd8859-5ea7-46d8-b95a-bc4f0df8b411"),
                                    InStore = 10,
                                    Online = 50,
                                    ProductId = new Guid("a4aa9101-5802-4ec9-a556-468a784dcff6"),
                                    Size = "S"
                                },
                                new
                                {
                                    Id = new Guid("c453bafc-dc2e-4b7e-a94c-f234b91c57f7"),
                                    InStore = 10,
                                    Online = 50,
                                    ProductId = new Guid("a4aa9101-5802-4ec9-a556-468a784dcff6"),
                                    Size = "M"
                                },
                                new
                                {
                                    Id = new Guid("0f62f318-c85f-4b9a-8580-a07321c57d85"),
                                    InStore = 10,
                                    Online = 50,
                                    ProductId = new Guid("a4aa9101-5802-4ec9-a556-468a784dcff6"),
                                    Size = "L"
                                },
                                new
                                {
                                    Id = new Guid("efdf260f-ef62-4e98-accc-bde0474acca8"),
                                    InStore = 10,
                                    Online = 50,
                                    ProductId = new Guid("097c365a-f057-4de1-aaaf-829516c25467"),
                                    Size = "6"
                                },
                                new
                                {
                                    Id = new Guid("fc8aff80-adf7-4232-97de-6309dd767352"),
                                    InStore = 10,
                                    Online = 50,
                                    ProductId = new Guid("097c365a-f057-4de1-aaaf-829516c25467"),
                                    Size = "9"
                                },
                                new
                                {
                                    Id = new Guid("7eec7336-179e-44a1-a3ca-809c2d988aca"),
                                    InStore = 10,
                                    Online = 50,
                                    ProductId = new Guid("097c365a-f057-4de1-aaaf-829516c25467"),
                                    Size = "10"
                                },
                                new
                                {
                                    Id = new Guid("f379d3ea-9b35-42b7-b659-e78b3f1b0e96"),
                                    InStore = 10,
                                    Online = 50,
                                    ProductId = new Guid("8a8038f9-9df9-4a7b-a76e-414ae1312827"),
                                    Size = "U"
                                });
                        });

                    b.Navigation("Brand");

                    b.Navigation("Category");

                    b.Navigation("Stocks");
                });
#pragma warning restore 612, 618
        }
    }
}
